export * from "./star";
export * from "./arrow";
export * from "./email";
export * from "./phone";
export * from "./close";
export * from "./check";
export * from "./versus";
export * from "./whatsapp";
export * from "./instagram";
